### ISSUE TITLE
there are some err when run the actions

### ISSUE THREAD

**Issue by atorber** [wechaty/puppet-xp#104]
@huan When I submit a new version，a series of errors have occurred here. Is there any dependency that needs to be updated？

Please help me check the problem, thank you！

ps:The same error occurs in my Mac M1, but it is normal in my windows server.

```
Run npm test
  npm test
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"

> wechaty-puppet-xp@1.11.0 test
> npm run lint && npm run test:unit


> wechaty-puppet-xp@1.11.0 lint
> npm run lint:es && npm run lint:ts && npm run lint:md


> wechaty-puppet-xp@1.11.0 lint:es
> eslint "src/**/*.ts" "tests/**/*.spec.ts" --ignore-pattern tests/fixtures/


> wechaty-puppet-xp@1.11.0 lint:ts
> tsc --isolatedModules --noEmit


> wechaty-puppet-xp@1.11.0 lint:md
> markdownlint README.md


> wechaty-puppet-xp@1.11.0 test:unit
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" tap "src/**/*.spec.ts" "tests/**/*.spec.ts"

TAP version 13
# Subtest: src/cjs.spec.ts
    # Subtest: ESM: codeRoot
        ok 1 - should exists "codeRoot"
        1..1
    ok 1 - ESM: codeRoot # time=5.9[2](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:2)8ms
    
    1..1
    # time=11.862ms
ok 1 - src/cjs.spec.ts # time=11.862ms

# Subtest: src/package-json.spec.ts
    # Subtest: Make sure the packageJson is fresh in source code
        ok 1 - packageJson should be empty in source code, only updated before publish to NPM
        1..1
    ok 1 - Make sure the packageJson is fresh in source code # time=5.577ms
    
D:\a\puppet-xp\puppet-xp\node_modules\@swc\core\index.js:1[3](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:3)7
    1..1
        return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
    # time=10.775ms
                        ^
ok 2 - src/package-json.spec.ts # time=10.775ms
Error: 

  x Illegal access to private class property.
    ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:71:5]
 71 | return this.#sidecar!
# Subtest: src/puppet-xp.spec.ts
    :        ^^^^^^^^^^^^^
    1..0 # no tests found
    `----
not ok 3 - src/puppet-xp.spec.ts # time=782.208ms

  ---
  x Illegal access to private class property.
  env: {}
    ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:9[4](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:4):[5](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:5)]
  file: src/puppet-xp.spec.ts
 94 | if (this.#sidecar) {
  timeout: 30000
    :     ^^^^^^^^^^^^^
  command: C:\hostedtoolcache\windows\node\1[6](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:6).14.2\x64\node.exe
    `----
  args:

    - src/puppet-xp.spec.ts
  x Illegal access to private class property.
  stdio:
    ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:96:[7](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:7)]
    - 0
 96 | await detach(this.#sidecar)
    - pipe
    :              ^^^^^^^^^^^^^
    - 2
    `----
  cwd: D:\a\puppet-xp\puppet-xp

  exitCode: 1
  x Illegal access to private class property.
  ...
    ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:97:7]

 97 | this.#sidecar = undefined
    : ^^^^^^^^^^^^^
    `----

  x Illegal access to private class property.
     ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:101:5]
 101 | this.#sidecar = new WeChatSidecar()
     : ^^^^^^^^^^^^^
     `----

  x Illegal access to private class property.
     ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:332:5]
 332 | this.#sidecar = undefined
     : ^^^^^^^^^^^^^
     `----

    at Compiler.transformSync (D:\a\puppet-xp\puppet-xp\node_modules\@swc\core\index.js:137:25)
    at Object.transformSync (D:\a\puppet-xp\puppet-xp\node_modules\@swc\core\index.js:217:21)
    at Object.transpile (D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\transpilers\swc.ts:14[8](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:8):3[9](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:9))
    at D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\index.ts:1276:35
    at Object.compile (D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\index.ts:1322:43)
    at transformSource (D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\esm.ts:380:37)
    at load (D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\esm.ts:280:51)
# Subtest: src/pure-functions/image-decrypt.spec.ts
    at async ESMLoader.load (node:internal/modules/esm/loader:359:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:47) {
    # Subtest: CJS: codeRoot()
        ok 1 - should exist ImageDecrypt
  code: 'GenericFailure'
        1..1
}
    ok 1 - CJS: codeRoot() # time=16.878ms
D:\a\puppet-xp\puppet-xp\node_modules\@swc\core\index.js:137
    
        return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
    1..1
                        ^
    # time=44.762ms
Error: 
ok 4 - src/pure-functions/image-decrypt.spec.ts # time=44.762ms
  x Illegal access to private class property.

    ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:71:5]
 71 | return this.#sidecar!
    :        ^^^^^^^^^^^^^
    `----

  x Illegal access to private class property.
    ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:94:5]
 94 | if (this.#sidecar) {
    :     ^^^^^^^^^^^^^
    `----

  x Illegal access to private class property.
    ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:96:7]
 96 | await detach(this.#sidecar)
    :              ^^^^^^^^^^^^^
    `----

  x Illegal access to private class property.
    ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:97:7]
 97 | this.#sidecar = undefined
    : ^^^^^^^^^^^^^
    `----

  x Illegal access to private class property.
     ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:[10](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:10)1:5]
 101 | this.#sidecar = new WeChatSidecar()
     : ^^^^^^^^^^^^^
     `----

  x Illegal access to private class property.
     ,-[D:/a/puppet-xp/puppet-xp/src/puppet-xp.ts:332:5]
 332 | this.#sidecar = undefined
     : ^^^^^^^^^^^^^
     `----

    at Compiler.transformSync (D:\a\puppet-xp\puppet-xp\node_modules\@swc\core\index.js:137:25)
    at Object.transformSync (D:\a\puppet-xp\puppet-xp\node_modules\@swc\core\index.js:217:21)
    at Object.transpile (D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\transpilers\swc.ts:148:39)
    at D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\index.ts:[12](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:12)76:35
    at Object.compile (D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\index.ts:[13](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:13)22:43)
    at transformSource (D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\esm.ts:380:37)
    at load (D:\a\puppet-xp\puppet-xp\node_modules\ts-node\src\esm.ts:280:51)
    at async ESMLoader.load (node:internal/modules/esm/loader:359:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:47) {
  code: 'GenericFailure'
}
# Subtest: tests/integration.spec.ts
    1..0 # no tests found
not ok 5 - tests/integration.spec.ts # time=907.846ms
  ---
  env: {}
  file: tests/integration.spec.ts
  timeout: 30000
  command: C:\hostedtoolcache\windows\node\16.[14](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:14).2\x64\node.exe
  args:
    - tests/integration.spec.ts
  stdio:
    - 0
    - pipe
    - 2
  cwd: D:\a\puppet-xp\puppet-xp
  exitCode: 1
  ...

1..5
# failed 2 of 5 tests
# time=3066.6[19](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:19)ms
--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------|---------|----------|---------|---------|-------------------
All files     |     [100](https://github.com/wechaty/puppet-xp/runs/6280416589?check_suite_focus=true#step:5:100) |      100 |     100 |     100 |                   
 code-root.js |     100 |      100 |     100 |     100 |                   
--------------|---------|----------|---------|---------|-------------------
Error: Process completed with exit code 1.
```

**Comment by huan** [comment]
1. Please make sure you are using Node.js v16+
2. try `rm -rf node_modules &&, npm install`

Please let me know if there still have problems after above two steps.

**Comment by atorber** [comment]
> 1. Please make sure you are using Node.js v16+
> 2. try `rm -rf node_modules && npm install`
> 
> Please let me know if there still have problems after above two steps.

Thank you,I will have a try later.
But I don't think it is useful,because it is runing well on my Windows server which is in working and I update the code in that computer and push the code to github,the ci actions is fail.Before this I clone xp use my m1 Mac,It is a new env,but have the same err with the ci actions.
It is really Strange.

**Comment by huan** [comment]
That's the meaning of the DEBUG 😄 

Feel free to let me know your updates.

**Comment by atorber** [comment]
I have try rm -rf node_modules && npm install,Even re clone the project，but But the problem remains.

At the same time, I only changed the package.json in my online branch from "version": "1.10.26" to "version": "1.10.27"  the errors are the same.

So I guess the problem is @swc？

```
PS C:\workspace\puppet-xp> npm run start

> wechaty-puppet-xp@1.10.26 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

C:\workspace\puppet-xp\node_modules\@swc\core\index.js:137
        return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
                        ^
Error: 
  × Illegal access to private class property.
    ╭─[C:/workspace/puppet-xp/src/puppet-xp.ts:71:5]
 71 │ return this.#sidecar!
    ·        ─────────────
    ╰────

  × Illegal access to private class property.
    ╭─[C:/workspace/puppet-xp/src/puppet-xp.ts:94:5]
 94 │ if (this.#sidecar) {
    ·     ─────────────
    ╰────

  × Illegal access to private class property.
    ╭─[C:/workspace/puppet-xp/src/puppet-xp.ts:96:7]
 96 │ await detach(this.#sidecar)
    ·              ─────────────
    ╰────

  × Illegal access to private class property.
    ╭─[C:/workspace/puppet-xp/src/puppet-xp.ts:97:7]
 97 │ this.#sidecar = undefined
    · ─────────────
    ╰────

  × Illegal access to private class property.
     ╭─[C:/workspace/puppet-xp/src/puppet-xp.ts:101:5]
 101 │ this.#sidecar = new WeChatSidecar()
     · ─────────────
     ╰────

  × Illegal access to private class property.
     ╭─[C:/workspace/puppet-xp/src/puppet-xp.ts:328:5]
 328 │ this.#sidecar = undefined
     · ─────────────
     ╰────

    at Compiler.transformSync (C:\workspace\puppet-xp\node_modules\@swc\core\index.js:137:25)
    at Object.transformSync (C:\workspace\puppet-xp\node_modules\@swc\core\index.js:217:21)
    at Object.transpile (C:\workspace\puppet-xp\node_modules\ts-node\src\transpilers\swc.ts:148:39)
    at C:\workspace\puppet-xp\node_modules\ts-node\src\index.ts:1276:35
    at Object.compile (C:\workspace\puppet-xp\node_modules\ts-node\src\index.ts:1322:43)
    at transformSource (C:\workspace\puppet-xp\node_modules\ts-node\src\esm.ts:380:37)
    at load (C:\workspace\puppet-xp\node_modules\ts-node\src\esm.ts:280:51)
    at async ESMLoader.load (node:internal/modules/esm/loader:407:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:11) {
  code: 'GenericFailure'
}
PS C:\workspace\puppet-xp> 
```

**Comment by atorber** [comment]
- Windows server
PS C:\workspace\puppet-xp> npm -v
7.22.0
PS C:\workspace\puppet-xp> node -v
v16.10.0
PS C:\workspace\puppet-xp> npm view typescript version
4.6.4
PS C:\workspace\puppet-xp> 

- Virtual Windows machine on M1

PS C:\workspace\puppet-xp> npm -v
8.5.5
PS C:\workspace\puppet-xp> node -v
v16.15.0
PS C:\workspace\puppet-xp> npm view typescript version
4.6.4
PS C:\workspace\puppet-xp>

**Comment by atorber** [comment]
I just update "version": "1.11.0" to "version": "1.11.1" at  https://github.com/wechaty/puppet-xp/actions/runs/2268076444

It success,So magical.

**Comment by huan** [comment]
Congratulations! 

That's definitely a bug that random happens, hope we can figure it out in the future!
