### ISSUE TITLE
iterator is not iterable

### ISSUE THREAD

**Issue by atorber** [wechaty/puppet-xp#109]
```
08:30:47 WARN Room findAll() message.ready() rejection: TypeError: iterator is not iterable
GError: message not found for id: cl31bnu72000grw7iff76hfm3
    at Function.from (file:///C:/Users/wechaty/Documents/GitHub/wechat-openai-qa-bot/node_modules/gerror/src/gerror/gerror.ts:69:17)       
    at PuppetXp.<anonymous> (file:///C:/Users/wechaty/Documents/GitHub/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45) {
  code: 2,
  details: 'GError: message not found for id: cl31bnu72000grw7iff76hfm3\n' +
    '    at Function.from (file:///C:/Users/wechaty/Documents/GitHub/wechat-openai-qa-bot/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at PuppetXp.<anonymous> (file:///C:/Users/wechaty/Documents/GitHub/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45)'
}
```

**Comment by atorber** [comment]
@huan This error appears to be that the current message is not queried when receiving onmessage. I checked the source code and cached the message after receiving the message. 
Theoretically, this problem will not occur during the running of the program
Do you have any ideas to solve the problem?

Please look at this question for me. Thank you

- The location file where the error was thrown

```
C:/Users/wechaty/Documents/GitHub/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45
```

- the code  where the error was thrown

```
          case 'message':
            puppet.on('message', async payload => {
              try {
                const msg = await this.Message.find({ id: payload.messageId })
                if (!msg) {
                  this.emit('error', GError.from('message not found for id: ' + payload.messageId))
                  return
                }

                this.emit('message', msg)

                const room     = msg.room()
                const listener = msg.listener()

                if (room) {
                  room.emit('message', msg)
                } else if (listener) {
                  listener.emit('message', msg)
                } else {
                  this.emit('error', GError.from('message without room and listener'))
                }
              } catch (e) {
                this.emit('error', GError.from(e))
              }
            })
            break
```

- the code xp store message

```
    const payload: PUPPET.payloads.Message = {
      id: cuid(),
      listenerId: toId,
      roomId,
      talkerId,
      text,
      timestamp: Date.now(),
      toId,
      type,
    }
    // console.info(payload)
    this.messageStore[payload.id] = payload
    this.emit('message', { messageId: payload.id })
```

**Comment by choogoo** [comment]
I have temporarily solved this problem. The reason is that there are enterprise-wechat rooms , and these rooms are not included in the rooms obtained by hook. Therefore, when these rooms have a speech, an error will be caused that the room cannot be found.
