### ISSUE TITLE
Get errors when receiving images. (running on windows server 2019)

### ISSUE THREAD

**Issue by htzziot** [wechaty/puppet-xp#116]
I'm running the puppet-xp on Windows Server 2019.
When receiving the image file from chat, it shows error below while the  dat file is actually there in the directory.
Does puppet-xp support Windows Server?

11:23:49 INFO message id=============: cl3b0s1w300023giu6lhb8de5
11:23:49 INFO message type===========: Image
[Error: ENOENT: no such file or directory, access 'C:\Users\Administrator\Documents\WeChat Files\wxid_vd79pq1b7eso22\FileStorage\Image\2022-05\ebd3bf5c038569371d222a8b27efff07.dat'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'access',
  path: 'C:\\Users\\Administrator\\Documents\\WeChat Files\\wxid_vd79pq1b7eso22\\FileStorage\\Image\\2022-05\\ebd3bf5c038569371d222a8b27efff07.dat'
}
监听消息失败 Error: no Base64 data
    at new FileBox (file:///C:/Users/Administrator/Desktop/wechat-openai-qa-bot-main/node_modules/file-box/src/file-box.ts:584:17)
    at Function.fromBase64 (file:///C:/Users/Administrator/Desktop/wechat-openai-qa-bot-main/node_modules/file-box/src/file-box.ts:237:12)
    at PuppetXp.messageImage (file:///C:/Users/Administrator/Desktop/wechat-openai-qa-bot-main/node_modules/wechaty-puppet-xp/src/puppet-xp.ts:598:21)
    at async WechatifiedUserClass.artwork (file:///C:/Users/Administrator/Desktop/wechat-openai-qa-bot-main/node_modules/wechaty/src/user-modules/image.ts:68:21)
    at async onMessage (file:///C:/Users/Administrator/Desktop/wechat-openai-qa-bot-main/src/handlers/on-message.js:34:16)
    at async WechatyImpl.<anonymous> (file:///C:/Users/Administrator/Desktop/wechat-openai-qa-bot-main/src/index.js:8:7)

**Comment by specialYmx** [comment]
我也碰到了这个问题在examples\ripe-wechaty.ts中接收图片处理报错

**Comment by jackatls** [comment]
这个应该是微信安装路径的问题，我也遇到了，修改一下src/puppet-xp.ts里的微信安装路径就行了

**Comment by specialYmx** [comment]
谢谢 ，现在不用xp协议了，用padlocal了。
顺便问下大佬清楚padlocal协议是不是现在只支持到20m左右的文件，怎么能支持大文件呢，我看padlocal官方说需要申请可是也不知道如何申请啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wechaty/puppet-xp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wechaty/puppet-xp] Get errors when receiving images. (running on windows server 2019) (Issue #116)





 
这个应该是微信安装路径的问题，我也遇到了，修改一下src/puppet-xp.ts里的微信安装路径就行了

**Comment by jackatls** [comment]
> 谢谢 ，现在不用xp协议了，用padlocal了。 顺便问下大佬清楚padlocal协议是不是现在只支持到20m左右的文件，怎么能支持大文件呢，我看padlocal官方说需要申请可是也不知道如何申请啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wechaty/puppet-xp" ***@***.***&gt;; 发送时间:&nbsp;2022年7月17日(星期天) 晚上10:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wechaty/puppet-xp] Get errors when receiving images. (running on windows server 2019) (Issue #116) 这个应该是微信安装路径的问题，我也遇到了，修改一下src/puppet-xp.ts里的微信安装路径就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

不是大佬,padlocal我个人用不起所以没有用

**Comment by specialYmx** [comment]
好的 tks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wechaty/puppet-xp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wechaty/puppet-xp] Get errors when receiving images. (running on windows server 2019) (Issue #116)





  
谢谢 ，现在不用xp协议了，用padlocal了。 顺便问下大佬清楚padlocal协议是不是现在只支持到20m左右的文件，怎么能支持大文件呢，我看padlocal官方说需要申请可是也不知道如何申请啊
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wechaty/puppet-xp" @.&gt;; 发送时间:&nbsp;2022年7月17日(星期天) 晚上10:12 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [wechaty/puppet-xp] Get errors when receiving images. (running on windows server 2019) (Issue #116) 这个应该是微信安装路径的问题，我也遇到了，修改一下src/puppet-xp.ts里的微信安装路径就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
不是大佬,padlocal我个人用不起所以没有用
