### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by crazyn2** [wechaty/puppet-xp#131]
OS: Windows 10
[WeChatSetup-v3.3.0.115.exe](https://github.com/wechaty/wechaty-puppet-xp/releases/download/v0.5/WeChatSetup-v3.3.0.115.exe)
node: 12.22.12
nvm: 1.x
```
PS C:\Users\ascha\Downloads\puppet-xp> npm start

> wechaty-puppet-xp@1.11.14 start C:\Users\ascha\Downloads\puppet-xp
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

Error: The specified module could not be found.
\\?\C:\Users\ascha\Downloads\puppet-xp\node_modules\@swc\core-win32-x64-msvc\swc.win32-x64-msvc.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\ascha\Downloads\puppet-xp\node_modules\@swc\core\binding.js:67:41)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechaty-puppet-xp@1.11.14 start: `cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wechaty-puppet-xp@1.11.14 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ascha\AppData\Roaming\npm-cache\_logs\2022-07-14T01_05_18_970Z-debug.log
```

**Comment by crazyn2** [comment]
问题临时解决了，用https://github.com/atorber/wechaty-puppet-xp-demo
