### ISSUE TITLE
Error: access violation accessing 0xfe5f6b10

### ISSUE THREAD

**Issue by shan501** [wechaty/puppet-xp#158]
I get the following error when trying to run my bot. 
```
19:02:35 ERR SidecarBody [SCRIPT_MESSAGRE_HANDLER_SYMBOL]() MessageType.Error: Error: access violation accessing 0xfe5f6b10
    at <anonymous> (frida/runtime/core.js:141)
    at <eval> (/script1.js:252)
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Error: access violation accessing 0xfe5f6b10
    at WeChatSidecar.[scriptMessageHandler] (file:///C:/Users/User/wechat/node_modules/sidecar/dist/esm/src/sidecar-body/sidecar-body.js:269:31)
    at C:\Users\User\wechat\node_modules\frida\dist\script.js:95:21
----- Agent Script Internal -----
Error: access violation accessing 0xfe5f6b10
    at <anonymous> (frida/runtime/core.js:141)
    at <eval> (/script1.js:252)
Emitted 'error' event on WeChatSidecar instance at:
    at WeChatSidecar.[scriptMessageHandler] (file:///C:/Users/User/wechat/node_modules/sidecar/dist/esm/src/sidecar-body/sidecar-body.js:275:26)
    at C:\Users\User\wechat\node_modules\frida\dist\script.js:95:21
```
My dependencies are the following 
```
	"dependencies": {
		"wechaty": "^1.20.2",
		"wechaty-puppet-xp": "^1.12.4"
	}
```

**Comment by JuoJuo** [comment]
same issue

**Comment by atorber** [comment]
This is an existing problem, we have temporarily dealt with this problem, please run `npm install wechaty-puppet-xp@1.12.6`  or `npm install wechaty-puppet-xp@latest` to upgrade, but it will take some time to solve the problem, please be patient
