### ISSUE TITLE
Process not found

### ISSUE THREAD

**Issue by zicheng-jscoder** [wechaty/puppet-xp#164]
GError: Process not found
    at Device.getProcess (D:\jdcoupon\node_modules\frida\dist\device.js:66:19)
    at async Device.getPid (D:\jdcoupon\node_modules\frida\dist\device.js:138:25)
    at async Device.attach (D:\jdcoupon\node_modules\frida\dist\device.js:120:21)
    at async Object.attach (D:\jdcoupon\node_modules\frida\dist\index.js:60:12)
    at async WeChatSidecar.[attatch] (D:\jdcoupon\node_modules\sidecar\dist\cjs\src\sidecar-body\sidecar-body.js:109:27)
    at async PuppetXp.onStart (D:\jdcoupon\node_modules\wechaty-puppet-xp\dist\cjs\src\puppet-xp.js:98:9)
    at async PuppetXp.start (D:\jdcoupon\node_modules\state-switch\dist\cjs\src\service-ctl\service-ctl.js:65:17)
    at async PuppetXp.start (D:\jdcoupon\node_modules\wechaty-puppet\dist\cjs\src\mixins\service-mixin.js:21:13)
    at async PuppetXp.start (D:\jdcoupon\node_modules\wechaty-puppet\dist\cjs\src\mixins\ready-mixin.js:16:13)
    at async WechatyImpl.start (D:\jdcoupon\node_modules\wechaty\dist\cjs\src\wechaty-mixins\puppet-mixin.js:74:21) {
  code: 2,

 "wechaty": "^1.20.2",
    "wechaty-puppet-xp": "^1.11.14"

昨天还是行，一样的代码今天就运行不起了

**Comment by tans** [comment]
你的微信是否有在运行， 我出现这个问题是没有打开微信。

然后如果登录微信了就会出现 Error: Script is destroyed. 我的也是昨天突然运行不起来了。

**Comment by zicheng-jscoder** [comment]
打开了的，重新安装@next版本就好了，但是运行的很不流畅，市场宕机

**Comment by tans** [comment]
是哪一个的@next

**Comment by choogoo** [comment]
Make sure your WeChat is logged in and the version is consistent with the corresponding one
