### ISSUE TITLE
cnpm install失败

### ISSUE THREAD

**Issue by cocktail18** [wechaty/puppet-xp#184]
执行 cnpm intall 失败

```
PS D:\workspace\cocktail\puppet-xp> cnpm install
√ Installed 17 packages on D:\workspace\cocktail\puppet-xp
√ Linked 797 latest versions fallback to D:\workspace\cocktail\puppet-xp\node_modules\.store\node_modules
√ Linked 46 public hoist packages to D:\workspace\cocktail\puppet-xp\node_modules
[1/10] scripts.postinstall @chatie/git-scripts@0.7.7 › git-scripts@^0.6.2 run "node bin/install", root: "D:\\workspace\\cocktail\\puppet-xp\\node_modules\\.store\\git-scripts@0.6.4\\node_modules\\git-scripts"
Not a git repository.
[1/10] scripts.postinstall @chatie/git-scripts@0.7.7 › git-scripts@^0.6.2 finished in 174ms
[2/10] scripts.postinstall @chatie/git-scripts@^0.7.7 run "node scripts/install.js", root: "D:\\workspace\\cocktail\\puppet-xp\\node_modules\\.store\\@chatie+git-scripts@0.7.7\\node_modules\\@chatie\\git-scripts"
[2/10] scripts.postinstall @chatie/git-scripts@^0.7.7 finished in 191ms
[3/10] scripts.postinstall @chatie/tsconfig@4.9.2 › pkg-jq@0.2.11 › node-jq@^1.12.0 run "npm run install-binary", root: "D:\\workspace\\cocktail\\puppet-xp\\node_modules\\.store\\node-jq@1.12.0\\node_modules\\node-jq"

> node-jq@1.12.0 install-binary
> node scripts/install-binary.js

node:internal/validators:163
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.resolve (node:path:167:9)
    at Object.<anonymous> (D:\workspace\cocktail\puppet-xp\node_modules\.store\npm-conf@1.1.3\node_modules\npm-conf\lib\defaults.js:31:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.16.0
[npminstall:runscript:error] @chatie/tsconfig@4.9.2 › pkg-jq@0.2.11 › node-jq@^1.12.0 scripts.postinstall run "npm run install-binary" error: Error [RunScriptError]: Run "C:\WINDOWS\system32\cmd.exe /d /s /c npm run install-binary" error, exit code 1
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  stdio: [Object],
  exitcode: 1
}
× Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c npm run install-binary" error, exit code 1
RunScriptError: Run "C:\WINDOWS\system32\cmd.exe /d /s /c npm run install-binary" error, exit code 1
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npminstall version: 7.4.0
npminstall argv: D:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\Administrator\.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com
```

**Comment by atorber** [comment]
请使用npm安装，由于网络限制可能下载失败，可以尝试连接vpn之后安装

**Comment by 532777032** [comment]
https://mp.weixin.qq.com/s/ygryXzhSLTwy7_lQd-VF3A 我也写教程也附上那部分不翻下不了的node_modules （只是那部分），我是存我网盘了，地址在文章中，但是你要是要复制node_modules 直接可以用，最好是win10的操作系统，我的node版本号18.12.1， 你考虑清楚后 要下在下
