### ISSUE TITLE
1.3.x MessageType.Error: Error: access violation accessing 0x21

### ISSUE THREAD

**Issue by HyperClockUp** [wechaty/puppet-xp#187]
```
11:24:17 ERR SidecarBody [SCRIPT_MESSAGRE_HANDLER_SYMBOL]() MessageType.Error: Error: access violation accessing 0x21
    at <anonymous> (frida/runtime/core.js:141)
    at onEnter (/script1.js:449)
node:events:491
      throw er; // Unhandled 'error' event
      ^

F:\code\oneRobot\node_modules\gerror\src\gerror\gerror.ts:69
      const e = new Error(payload)
                ^

GError: {}
    at Function.from (F:\code\oneRobot\node_modules\gerror\src\gerror\gerror.ts:69:17)
    at PuppetXp.emit (F:\code\oneRobot\node_modules\wechaty-puppet\src\puppet\puppet-skeleton.ts:131:21)
    at WeChatSidecar.<anonymous> (F:\code\oneRobot\node_modules\wechaty-puppet-xp\src\puppet-xp.ts:139:40)
    at WeChatSidecar.emit (node:events:513:28)
    at WeChatSidecar.emit (node:domain:489:12)
    at WeChatSidecar.[scriptMessageHandler] (F:\code\oneRobot\node_modules\sidecar\src\sidecar-body\sidecar-body.ts:406:16)
    at <anonymous> (f:\code\oneRobot\node_modules\frida\dist\script.js:95:21)
Emitted 'error' event on WechatyImpl instance at:
      return super.emit('error', gerror)
                   ^

Error
    at WechatyImpl.emit (F:\code\oneRobot\node_modules\wechaty\src\wechaty-mixins\gerror-mixin.ts:60:20)
    at PuppetXp.<anonymous> (F:\code\oneRobot\node_modules\wechaty\src\wechaty-mixins\puppet-mixin.ts:212:20)
    at PuppetXp.emit (node:events:513:28)
    at PuppetXp.emit (node:domain:489:12)
    at PuppetXp.emit (F:\code\oneRobot\node_modules\wechaty-puppet\src\puppet\puppet-skeleton.ts:142:18)
    at WeChatSidecar.<anonymous> (F:\code\oneRobot\node_modules\wechaty-puppet-xp\src\puppet-xp.ts:139:40)
    [... lines matching original stack trace ...]
    at <anonymous> (f:\code\oneRobot\node_modules\frida\dist\script.js:95:21) {
  code: 2,
  details: 'F:\\code\\oneRobot\\node_modules\\gerror\\src\\gerror\\gerror.ts:69\n' +
    '      const e = new Error(payload)\n' +
    '                ^\n' +
    '\n' +
    'GError: {}\n' +
    '    at Function.from (F:\\code\\oneRobot\\node_modules\\gerror\\src\\gerror\\gerror.ts:69:17)\n' +
    '    at PuppetXp.emit (F:\\code\\oneRobot\\node_modules\\wechaty-puppet\\src\\puppet\\puppet-skeleton.ts:131:21)\n' +
    '    at WeChatSidecar.<anonymous> (F:\\code\\oneRobot\\node_modules\\wechaty-puppet-xp\\src\\puppet-xp.ts:139:40)\n' +
    '    at WeChatSidecar.emit (node:events:513:28)\n' +
    '    at WeChatSidecar.emit (node:domain:489:12)\n' +
    '    at WeChatSidecar.[scriptMessageHandler] (F:\\code\\oneRobot\\node_modules\\sidecar\\src\\sidecar-body\\sidecar-body.ts:406:16)\n' +
    '    at <anonymous> (f:\\code\\oneRobot\\node_modules\\frida\\dist\\script.js:95:21)'
}
error Command failed with exit code 1.
```

**Comment by atorber** [comment]
Have you upgraded the WeChat client to 3.9.2.23？

**Comment by HyperClockUp** [comment]
> Have you upgraded the WeChat client to 3.9.2.23？

yes，I download the WeChat from the REAME. 

To prevent problems caused by other dependencies, I first used ```yarn upgrade``` to keep wechaty the latest version.
And then I executed ```yarn add wechaty-puppet-xp@next```.

This error does not occur every time, sometimes during startup (but you can see the printed log of the contact list), and sometimes after a successful run of about a minute.

But when I downgrade back to the previous version, everything goes well.

**Comment by blacklips** [comment]
It must appear when it receives the picture

**Comment by MungJI** [comment]
> It must appear when it receives the picture

wo also have this error @atorber
