### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined

### ISSUE THREAD

**Issue by duanxr** [wechaty/puppet-xp#45]
Just followed the documentation and executed **npm run start:ripe**, and got these : 
```
D:\OpenSource\puppet-xp>npm run start:ripe

> wechaty-puppet-xp@0.10.1 start:ripe D:\OpenSource\puppet-xp
> cross-env WECHATY_LOG=verbose NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ripe-wechaty.ts

18:05:32 INFO Config registering process.on("unhandledRejection") for development/debug
18:05:58 VERB Config constructor()
18:05:58 VERB user/mixins/poolify poolifyMixin(EventEmitter)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(PoolifiedMixin)
18:05:58 VERB user/mixins/validation validationMixin(ContactMixin)
18:05:58 VERB user/mixins/poolify poolifyMixin(ContactImpl)
18:05:58 VERB user/mixins/validation validationMixin(ContactSelfMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EmptyBase)
18:05:58 VERB user/mixins/validation validationMixin(FavoriteMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EventEmitter)
18:05:58 VERB user/mixins/validation validationMixin(FriendshipMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EmptyBase)
18:05:58 VERB user/mixins/validation validationMixin(ImageMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EmptyBase)
18:05:58 VERB user/mixins/validation validationMixin(LocationMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EmptyBase)
18:05:58 VERB user/mixins/validation validationMixin(UrlLinkMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EmptyBase)
18:05:58 VERB user/mixins/validation validationMixin(MiniProgramMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EventEmitter)
18:05:58 VERB user/mixins/validation validationMixin(MessageMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EmptyBase)
18:05:58 VERB user/mixins/validation validationMixin(MomentMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EmptyBase)
18:05:58 VERB user/mixins/validation validationMixin(MoneyMixin)
18:05:58 VERB user/mixins/poolify poolifyMixin(EventEmitter)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(PoolifiedMixin)
18:05:58 VERB user/mixins/validation validationMixin(RoomMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EmptyBase)
18:05:58 VERB user/mixins/validation validationMixin(RoomInvitationMixin)
18:05:58 VERB user/mixins/poolify poolifyMixin(EmptyBase)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(PoolifiedMixin)
18:05:58 VERB user/mixins/validation validationMixin(TagMixin)
18:05:58 VERB user/mixins/wechatify wechatifyMixin(EmptyBase)
18:05:58 VERB user/mixins/validation validationMixin(DelayMixin)
18:05:59 VERB wechaty-puppet-service monkeyPatchMetadataFromHttp2Headers()
18:05:59 VERB PuppetSkelton constructor({})
18:05:59 VERB PuppetMemoryMixin constructor()
18:05:59 VERB PuppetStateMixin constructor() #1
18:05:59 VERB StateSwitch constructor(PuppetBusyIndicator, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
18:05:59 VERB StateSwitch constructor(PuppetState, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
18:05:59 VERB WatchdogAgent constructor(877b2afe-66ca-4c9b-beb7-578937519778)
18:05:59 VERB WatchdogAgent constructor() watchdog timeout set to 60 seconds
18:05:59 VERB PuppetCacheMixin constructor({})
18:05:59 VERB CacheAgent constructor()
18:05:59 VERB PuppetLoginMixin constructor()
18:05:59 VERB PuppetContactMixin constructor()
18:05:59 VERB PuppetRoomMemberMixin constructor()
18:05:59 VERB PuppetRoomMixin constructor()
18:05:59 VERB PuppetFriendshipMixin constructor()
18:05:59 VERB PuppetTagMixin constructor()
18:05:59 VERB PuppetRoomInvitationMixin constructor()
18:05:59 VERB PuppetMessageMixin constructor()
18:05:59 VERB PuppetMiscMixin constructor()
18:05:59 VERB Puppet constructor({})
18:05:59 VERB PuppetXp constructor({})
18:05:59 VERB WechatyBuilder constructor()
18:05:59 VERB WechatyBuilder singleton()
18:05:59 VERB WechatyBuilder newInstance()
18:05:59 VERB Wechaty constructor()
18:05:59 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
18:05:59 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
18:05:59 VERB Wechaty on(scan, listener) registering... listenerCount: 0
18:05:59 VERB Wechaty on(login, listener) registering... listenerCount: 0
18:05:59 VERB Wechaty on(logout, listener) registering... listenerCount: 0
18:05:59 VERB Wechaty on(message, listener) registering... listenerCount: 0
18:05:59 VERB Wechaty start()
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at checkListener (events.js:135:11)
    at _addListener (events.js:433:3)
    at StateSwitch.addListener (events.js:497:10)
    at WechatyImpl.start (file:///D:/OpenSource/puppet-xp/node_modules/wechaty/src/wechaty.ts:762:20)
    at file:///D:/OpenSource/puppet-xp/examples/ripe-wechaty.ts:65:5
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
18:05:59 VERB Wechaty init() Raven disabled (import("raven") failed)
```

I got the same error with ``npm start``, did I miss something?

**Comment by huan** [comment]
You are running Wechaty v1.x, which needs the PR to be merged to be supported by the Puppet XP:

- #46
