### ISSUE TITLE
但当接收到 图片之后，报出如下错误，是我什么地方的配置有问题吗？

### ISSUE THREAD

**Issue by JustinKyo** [wechaty/puppet-xp#53]
直接clone下来运行的，文本信息接收和发送都没问题，但当接收到 图片之后，报出如下错误，是我什么地方的配置有问题吗？
-------
RECV: Message#Image[🗣Contact@👥Room<Kyo工会>]
1f
TypeError: Cannot read properties of undefined (reading 'name')
at getNameExtension (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\wechaty-puppet-xp\dist\cjs\src\pure-functions\image-decrypt.js:83:7)
at ImageDecrypt (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\wechaty-puppet-xp\dist\cjs\src\pure-functions\image-decrypt.js:16:27)
at PuppetXp.messageFile (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\wechaty-puppet-xp\dist\cjs\src\puppet-xp.js:354:71)
at WechatifiedUserClass.toFileBox (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\wechaty\dist\cjs\src\user-modules\message.js:785:51)
at WechatyImpl.onMessage (D:\gitlab_new_test\wechaty-puppet-xp-demo\main.js:112:38)
Error: ImageDecrypt fail
at ImageDecrypt (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\wechaty-puppet-xp\dist\cjs\src\pure-functions\image-decrypt.js:28:11)
at PuppetXp.messageFile (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\wechaty-puppet-xp\dist\cjs\src\puppet-xp.js:354:71)
at WechatifiedUserClass.toFileBox (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\wechaty\dist\cjs\src\user-modules\message.js:785:51)
at WechatyImpl.onMessage (D:\gitlab_new_test\wechaty-puppet-xp-demo\main.js:112:38)
Error: no Base64 data
at new FileBox (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\file-box\dist\cjs\src\file-box.js:412:27)
at Function.fromBase64 (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\file-box\dist\cjs\src\file-box.js:153:16)
at PuppetXp.messageFile (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\wechaty-puppet-xp\dist\cjs\src\puppet-xp.js:363:35)
at WechatifiedUserClass.toFileBox (D:\gitlab_new_test\wechaty-puppet-xp-demo\node_modules\wechaty\dist\cjs\src\user-modules\message.js:785:51)
at WechatyImpl.onMessage (D:\gitlab_new_test\wechaty-puppet-xp-demo\main.js:112:38)

**Comment by hanyu8866** [comment]
解析缩略图没有匹配到类型
