### ISSUE TITLE
如何获取群聊提及到我的人的ID等信息呢？

### ISSUE THREAD

**Issue by zhuangzihan** [wechaty/puppet-xp#59]
1、使用Contact.find()函数，参数为微信名时（微信名可重复），可能会找到多个数值，且只返回一个
2、同一个对话框，talkerId和toId都是固定的，不管是哪个人发，机器人永远是toId，这也导致了Message.self()方法一直是false
3、Message.alias()获取到的都为空，不管有无备注

**Comment by ericcug** [comment]
This issue should have been fixed by PR #66 and #76

**Comment by WukongZeming** [comment]
> 

我试过了手动替换代码到最新（2月15日）【因为无论我如何npm upgrade，哪怕是指定版本号，都会给我安装 1.10.2版本，但我看你们最新版本是 1.10.19】
然而题主的这几个问题依然在。（我是使用Python-wechaty，已经更新到0.85版本）
```
2022-03-12 13:35:09,680 - Contact - INFO - Contact alias <None>
2022-03-12 13:35:09,689 - Contact - INFO - Contact alias(None) rejected: ('can"t get contact<wxid_a6xxa7n11u5j22> alias', None, None)
您还没有为联系人设置任何别名大兄弟666
```
群里面的群昵称也不行，导致 mention总是@对方的名称，而非群备注
```
2022-03-12 13:36:49,665 - Room - INFO - Room say <dong, ['wxid_a6xxa7n11u5j22']>
2022-03-12 13:36:49,666 - Contact - INFO - Contact alias <None>
2022-03-12 13:36:49,668 - Contact - INFO - Contact alias(None) rejected: ('can"t get contact<wxid_a6xxa7n11u5j22> alias', None, None)
```
不仅如此，现在同一个对话窗口，自己账号从另外设备发出的消息自动同步过来的，也会被认为是对方发来的，也就是msg.is_self()还是不能正确取值

另外file_box也是不支持的……
```
Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...not defined")>) at C:\Users\Zhao\AppData\Local\Programs\Python\Python39\lib\site-packages\pyee\asyncio.py:65
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...not defined")>) at C:\Users\Zhao\AppData\Local\Programs\Python\Python39\lib\site-packages\pyee\asyncio.py:65>
Traceback (most recent call last):
  File "C:\Users\Zhao\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Zhao\AppData\Local\Programs\Python\Python39\lib\site-packages\pyee\asyncio.py", line 71, in callback
    self.emit("error", exc)
  File "C:\Users\Zhao\AppData\Local\Programs\Python\Python39\lib\site-packages\wechaty\wechaty.py", line 289, in emit
    return super().emit(event, *args, **kwargs)
  File "C:\Users\Zhao\AppData\Local\Programs\Python\Python39\lib\site-packages\pyee\base.py", line 179, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "C:\Users\Zhao\AppData\Local\Programs\Python\Python39\lib\site-packages\pyee\base.py", line 139, in _emit_handle_potential_error
    raise error
  File "C:\Users\Zhao\puppet-try.py", line 53, in on_message
    await msg.say(file_box)
NameError: name 'file_box' is not defined
```
