### ISSUE TITLE
重大bug：联系人只要一个动作就能让puppet-xp终止服务

### ISSUE THREAD

**Issue by WukongZeming** [wechaty/puppet-xp#62]
只要收到视频或者语音通话邀请，puppet-xp服务就会报错终止，报错信息如下：
```
12:00:00 ERR SidecarBody [SCRIPT_MESSAGRE_HANDLER_SYMBOL]() MessageType.Error: Error: access violation accessing 0x0
    at onEnter (/script1.js:450)
```
程序端（python-wechaty）信息：
```
2022-01-21 12:00:00,958 - PuppetService - INFO - receive error info <{'gerror': '{"code":2,"details":"GError: {}\\n    at Function.from (file:///C:/Users/Zhao/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/node_modules/gerror/dist/esm/src/gerror/gerror.js:80:23)\\n    at PuppetXp.emit (file:///C:/Users/Zhao/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:92:27)\\n    at WeChatSidecar.<anonymous> (file:///C:/Users/Zhao/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/dist/esm/src/puppet-xp.js:196:44)\\n    at WeChatSidecar.emit (node:events:390:28)\\n    at WeChatSidecar.[scriptMessageHandler] (file:///C:/Users/Zhao/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/node_modules/sidecar/dist/esm/src/sidecar-body/sidecar-body.js:275:26)\\n    at C:\\\\Users\\\\Zhao\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\wechaty-puppet-xp\\\\node_modules\\\\frida\\\\dist\\\\script.js:95:21","message":"{}","name":"GError","stack":"GError: {}\\n    at Function.from (file:///C:/Users/Zhao/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/node_modules/gerror/dist/esm/src/gerror/gerror.js:80:23)\\n    at PuppetXp.emit (file:///C:/Users/Zhao/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:92:27)\\n    at WeChatSidecar.<anonymous> (file:///C:/Users/Zhao/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/dist/esm/src/puppet-xp.js:196:44)\\n    at WeChatSidecar.emit (node:events:390:28)\\n    at WeChatSidecar.[scriptMessageHandler] (file:///C:/Users/Zhao/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/node_modules/sidecar/dist/esm/src/sidecar-body/sidecar-body.js:275:26)\\n    at C:\\\\Users\\\\Zhao\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\wechaty-puppet-xp\\\\node_modules\\\\frida\\\\dist\\\\script.js:95:21"}'}>
Traceback (most recent call last):
  File "C:\Users\Zhao\python-wechaty-getting-started\examples\xiaoyan-bot.py", line 138, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Zhao\python-wechaty-getting-started\examples\xiaoyan-bot.py", line 133, in main
    await bot.start()
  File "C:\Python310\lib\site-packages\wechaty\wechaty.py", line 394, in start
    await self.puppet.start()
  File "C:\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 929, in start
    await self._listen_for_event()
  File "C:\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 1029, in _listen_for_event
    payload = EventErrorPayload(**payload_data)
TypeError: __init__() got an unexpected keyword argument 'gerror'
```

**Comment by binsee** [comment]
不用包括 puppet-xp 在内的任何第三方工具，直接用微信接收或发送视频聊天，微信是否会崩溃呢？

我这边是会崩溃的（多个微信版本都会崩溃，包括最新版），是视频采集设备驱动引发的故障，与 puppet-xp 无关，不知道你那边是否也如此？

如果程序崩溃，出现错误报告窗口的话，可以将错误报告内的第一个txt文件内容发上来，作为参考

内容如：

```txt
微信 3.30.0115 2022/1/28 08:25:52
----------------------------------------
Type: EXCEPTION_ACCESS_VIOLATION
Error: Read address 0x00000060
Address: 10002B30

CallStack:
avmC875virtualvideocapture + 2B30
quartz + 7302C
quartz + 8271C
quartz + 82739
quartz + 843CD
WeChatWin + AD789E
WeChatWin + AB29C6
WeChatWin + AD76EC
WeChatWin + 156F68
KERNEL32 + 16739
ntdll + 68E7F
show in line:avmC875virtualvideocapture + 2B30 quartz + 7302C quartz + 8271C quartz + 82739 quartz + 843CD WeChatWin + AD789E WeChatWin + AB29C6 WeChatWin + AD76EC WeChatWin + 156F68 KERNEL32 + 16739 ntdll + 68E7F 

Regs:
EAX=00000000, EBX=0D0FAD30, ECX=0DA7C228, EDX=0500D3C0
ESI=0D15CF88, EDI=0D15CF3C, EBP=0DA3F674, ESP=0DA3F65C, EIP=10002B30
```

**Comment by ericcug** [comment]
Try latest code? This issue cannot be reproduced.

**Comment by atorber** [comment]
When you are invited to join the group, you will exit by mistake

```
12:37:00 INFO StarterBot {"_events":{},"_eventsCount":0,"id":"cl2y8fhwq000d0svo4sl7fmtx","payload":{"id":"cl2y8fhwq000d0svo4sl7fmtx","listenerId":"wxid_3nowrr7t7c5d22","roomId":"","talkerId":"wxid_i6693adu7fi822","text":"<msg><appmsg appid=\"\" sdkver=\"\"><title><![CDATA[邀请你加入群聊]]></title><des><![CDATA[\"阿冰 🧊\"邀请你加入群聊\"秋月枫舍二期抗疫团购  专供🚚\"，进入可查看详情。]]></des><action>view</action><type>5</type><showtype>0</showtype><content></content><url><![CDATA[https://support.weixin.qq.com/cgi-bin/mmsupport-bin/addchatroombyinvite?ticket=A7SZ4utk9IFHaCXTz%2BRfMQ%3D%3D]]></url><thumburl><![CDATA[http://wx.qlogo.cn/mmcrhead/iaL1VhpNr1c4MLZNCWqibZGpJtSqJapqZkkonFu6ickZJs38tDLjTiazp7icepkRskrlWPS7G5FU4W6ada4JJMBlTEicNFrMiapP8MC/0]]></thumburl><lowurl></lowurl><appattach><totallen>0</totallen><attachid></attachid><fileext></fileext></appattach><extinfo></extinfo></appmsg><appinfo><version></version><appname></appname></appinfo></msg>","timestamp":1652071020651,"toId":"wxid_3nowrr7t7c5d22","type":14}}
12:37:16 WARN Room findAll() message.ready() rejection: TypeError: iterator is not iterable
GError: message not found for id: cl2y8fts2000e0svocfyp45o4
    at Function.from (file:///C:/wechat-openai-qa-bot-main/node_modules/gerror/src/gerror/gerror.ts:69:17)
    at PuppetXp.<anonymous> (file:///C:/wechat-openai-qa-bot-main/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45) {
  code: 2,
  details: 'GError: message not found for id: cl2y8fts2000e0svocfyp45o4\n' +
    '    at Function.from (file:///C:/wechat-openai-qa-bot-main/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at PuppetXp.<anonymous> (file:///C:/wechat-openai-qa-bot-main/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45)'
}
```

**Comment by atorber** [comment]
```
13:02:48 INFO StarterBot {"_events":{},"_eventsCount":0,"id":"cl2y9co9y000eg4voa08nfkh0","payload":{"id":"cl2y9co9y000eg4voa08nfkh0","listenerId":"wxid_3no75d22","roomId":"","talkerId":"wxid_ks1922","text":"你已添加了秋月团长 ，现在可以开始聊天了。","timestamp":1652072568550,"toId":"wxid_5d22","type":0}}
13:02:48 INFO StarterBot {"_events":{},"_eventsCount":0,"id":"cl2y9co9y000dg4vocvm35ne0","payload":{"id":"cl2y9co9y000dg4vocvm35ne0","listenerId":"wxid_c5d22","roomId":"","talkerId":"fmessage","text":"<msg fromusername=\"wxid_bgis1922\" encryptusername=\"v3_020b3826fd030100000000002214397c30d58d000000501ea9a3dba12f95f6b60a0536a1adb690cb9647fd8496acdd7313a73a226444ad2f66ab5ef38d53b22a2f2804111573017358fdc286ea593eae59e80d1d0d9697ac6fd12a01740cbce158a6@stranger\" fromnickname=\"秋月团长\" content=\"我是群聊“秋月枫舍二期抗疫团购专供🚚”的团长 到货信息请看群公告\" fullpy=\"qiuyuetuanchang\" shortpy=\"QYTC\" imagestatus=\"3\" scene=\"14\" country=\"CN\" province=\"Shanghai\" city=\"\" sign=\"消息太多回复不过来，如未回复请谅解。 到货群内通知❗️\" percard=\"1\" sex=\"2\" alias=\"GY-KOREA\" weibo=\"\" albumflag=\"0\" albumstyle=\"0\" albumbgimgid=\"\" snsflag=\"257\" snsbgimgid=\"http://shmmsns.qpic.cn/mmsns/IBqXYPaCau8KKVxOAWhVTo13Yc9Ag5UlF4TuG8S8m0iaLNic1ttTp8RNxxiaEhhYy0dDAmn3xWNe1Q/0\" snsbgobjectid=\"13839410295955009884\" mhash=\"36394a0802854bfbe8deab50c50d9252\" mfullhash=\"36394a0802854bfbe8deab50c50d9252\" bigheadimgurl=\"http://wx.qlogo.cn/mmhead/ver_1/Lb7ibELComelib8x0YSUicr7JgZULqClCUib4VaDwCveaaKz4DibmvgI0N8ndDkPdaDQ3aicRrP5o4AcOCT45wB9HrQHnILtj4dbcezvhoedLib1SQ/0\" smallheadimgurl=\"http://wx.qlogo.cn/mmhead/ver_1/Lb7ibELComelib8x0YSUicr7JgZULqClCUib4VaDwCveaaKz4DibmvgI0N8ndDkPdaDQ3aicRrP5o4AcOCT45wB9HrQHnILtj4dbcezvhoedLib1SQ/96\" ticket=\"v4_000b708f0b040000010000000000b9dc09eaa5b12f00369a66a078621000000050ded0b020927e3c97896a09d47e6e9e034191ebf7471d21ca20e56ba3e4c6adce0b3560cc05ff50ef3746b11e30e368108f6fa10f9e33107659fb841be2c24d5fb942ddb69e0d7024194163fa4200d131efbfe1ea38d46c63690be56d96b72af927ced7fddd688ef15ada101c5783a31536b98aba02a1b1@stranger\" opcode=\"2\" googlecontact=\"\" qrticket=\"\" chatroomusername=\"24360132672@chatroom\" sourceusername=\"\" sourcenickname=\"\" sharecardusername=\"\" sharecardnickname=\"\" cardversion=\"\" extflag=\"0\"><brandlist count=\"0\" ver=\"774846915\"></brandlist></msg>","timestamp":1652072568550,"toId":"wxid_3nd22","type":0}}
```

**Comment by OatLatte** [comment]
请问这个问题解决了吗?
