### ISSUE TITLE
MessageType.Error: Error: access violation accessing 0x53013f

### ISSUE THREAD

**Issue by liuxiaojinla** [wechaty/puppet-xp#64]
10:41:46 ERR SidecarBody [SCRIPT_MESSAGRE_HANDLER_SYMBOL]() MessageType.Error: Error: access violation accessing 0x53013f
    at <anonymous> (frida/runtime/core.js:138)
    at <eval> (/script1.js:227)
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: Error: access violation accessing 0x53013f
    at WeChatSidecar.[scriptMessageHandler] (C:\Users\NINGMEI\Desktop\wechaty\node_modules\sidecar\dist\cjs\src\sidecar-body\sidecar-body.js:291:31)
    at C:\Users\NINGMEI\Desktop\wechaty\node_modules\frida\dist\script.js:95:21
----- Agent Script Internal -----
Error: access violation accessing 0x53013f
    at <anonymous> (frida/runtime/core.js:138)
    at <eval> (/script1.js:227)
Emitted 'error' event on WeChatSidecar instance at:
    at WeChatSidecar.[scriptMessageHandler] (C:\Users\NINGMEI\Desktop\wechaty\node_modules\sidecar\dist\cjs\src\sidecar-body\sidecar-body.js:297:26)
    at C:\Users\NINGMEI\Desktop\wechaty\node_modules\frida\dist\script.js:95:21

**Comment by binsee** [comment]
Maybe #70 will fix this.
