### ISSUE TITLE
SyntaxError: The requested module 'qrcode' does not provide an export named 'toF ileStream'

### ISSUE THREAD

**Issue by lightlizm** [wechaty/puppet-xp#95]
安装以下命令安装xp ： 
git clone https://github.com/wechaty/wechaty-puppet-xp.git
cd wechaty-puppet-xp
npm install

运行一下命令，报错：
### C:\nodejs\wechaty-puppet-xp>node --loader ts-node/esm C:\nodejs\wechaty-puppet-x
p\examples\ding-dong-bot.ts
(node:3944) ExperimentalWarning: --experimental-loader is an experimental featur
e. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///C:/nodejs/wechaty-puppet-xp/node_modules/file-box/dist/esm/src/qrcode.js
:10
import { toFileStream } from 'qrcode';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'qrcode' does not provide an export named 'toF
ileStream'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)

**Comment by huan** [comment]
We will recommend using https://github.com/wechaty/getting-started for getting started instead of cloning this repo because this repo is for **puppet development**.
