### ISSUE TITLE
系统运行时，将微信机器人添加到新的群组里会报错

### ISSUE THREAD

**Issue by jyxinye** [wechaty/puppet-xp#98]
是不支持，在运营是将微信添加到微信群吗？

 WARN Message ready() payload.talkerId not exist! See: https://github.com/wechaty/puppet/issues/187
Puppet: wechaty-puppet@1.10.20
Error
    at WechatifiedUserClass.ready (file:///C:/Users/15043/jy/node_modules/wechaty/dist/esm/src/user-modules/message.js:677:27)
    at async Promise.all (index 0)
    at async Function.findAll (file:///C:/Users/15043/jy/node_modules/wechaty/dist/esm/src/user-modules/message.js:74:13)
    at async Function.find (file:///C:/Users/15043/jy/node_modules/wechaty/dist/esm/src/user-modules/message.js:55:29)
    at async PuppetXp.<anonymous> (file:///C:/Users/15043/jy/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:214:45)
15:04:32 WARN Room findAll() message.ready() rejection: TypeError: iterator is not iterable
15:04:32 WARN Room findAll() message.ready() rejection: TypeError: iterator is not iterable
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);

**Comment by xeyn** [comment]
需要升级 wechaty-puppet-xp 到最新

**Comment by liuweiGL** [comment]
wechaty-puppet-xp@1.10.26 还是会报这个 warn。

**Comment by atorber** [comment]
> wechaty-puppet-xp@1.10.26 还是会报这个 warn 。

Try run `npm install wechaty-puppet-xp@next` use the latest version ,if the warn still exists，let me know.
